import React from 'react'
import styled from 'styled-components'
import logo2 from '../Assets/history.jpeg'
import logo3 from '../Assets/timelinebg.jpeg'
import TimeLineComponent from './TimeLineComponent'

const Container = styled.div`
    width: 100%;
    height: 80vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        color: #fff;
        font-size: 5vw;
    }
`
const HistoryContainer = styled.div`
    width: 100%;
    min-height: 100vh;
`
const Paragraph = styled.p`
    @media (max-width:480px) {
       font-size: 1.2rem; 
       line-height: 40px;
    }
    font-size: 1.5vw;
    line-height: 30px;
    font-family: 'Raleway', sans-serif;
`
const SecondContainer = styled.div`
    width: 100%;
    height: 100vh;
    padding: 5%;
    font-weight: 500;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
`
const TimelineComponent = styled.div`
    width: 100%;
    min-height: 100vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo3}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
`
function History() {

  return (
    <HistoryContainer>
        <Container>
            <h1>OUR HISTORY</h1>
        </Container>

        <SecondContainer>
            <Paragraph>
                The Manufacturers Association of Nigeria (MAN) was established in May, 1971 as a company limited by guarantee. The establishment of the Association was motivated by the desire to have a focal point of communication and consultation between industry on the one hand, and the government and general public on the other. Hitherto, there was no institutional organ whose central focus was to give meaning to the interests, problems and aspirations of the manufacturing sector.
            </Paragraph>

            <Paragraph>
                The establishment of the Manufacturers Association of Nigeria was to provide a platform for the private sector to formulate and articulate policy suggestions that would be complementary to governments efforts at policy formulation. MAN is in business to create a climate of opinion in this country in which manufacturers can operate efficiently and profitably for the benefit of all. As the collective voice of its members, MAN was established to promote and protect manufacturers collective interests.
            </Paragraph>

            <Paragraph>
                The establishment of the Manufacturers Association of Nigeria was therefore seen as a forum for the private sector to formulate and articulate policy suggestions that would be complementary to government’s efforts at policy formulation. MAN is in business to create a climate of opinion in this country in which manufacturers can operate efficiently and profitably for the benefit of all. As the collective voice of its members, MAN was established to promote and protect manufacturers’ collective interests.
            </Paragraph>
        </SecondContainer>

        <TimelineComponent>
            <TimeLineComponent/>
        </TimelineComponent>
    </HistoryContainer>
  )
}

export default History