import React from 'react'
import styled from 'styled-components'
import logo2 from '../Assets/history.jpeg'
import logo3 from '../Assets/timelinebg.jpeg'
import Footer from './Footer'
import Nav from './Nav'
import TimeLineComponent from './TimeLineComponent'

const Container = styled.div`
    @media (max-width:480px) {
        height: 70vh;
    }
    width: 100%;
    height: 80vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        color: #fff;
        font-size: 5vw;
    }
`
const HistoryContainer = styled.div`
    width: 100%;
    min-height: 100vh;
    overflow: hidden;
`
const Paragraph = styled.p`
    @media (max-width:480px) {
       font-size: 1.2rem; 
       line-height: 40px;
    }
    font-size: 1.5vw;
    line-height: 30px;
    font-family: 'Raleway', sans-serif;
`
const SecondContainer = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 100vh;
    padding: 5%;
    font-weight: 500;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
`
const TimelineComponent = styled.div`
    width: 100%;
    min-height: 100vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo3}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
`
const Mission = styled.div`
    width: 100%;
    min-height: 100vh;
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 20%;
    flex-direction: column;
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        font-family: 'Lato', sans-serif;
        margin-top: 5%;
        font-size: 2vw;
        font-weight: 900;
    }
    li{
        @media (max-width:480px) {
            font-size: 1.2rem;
        }
        margin-top: 2%;
        margin-left: 2%;
        font-family: 'Raleway', sans-serif;
        font-size: 1.5vw;
    }

    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
        }
        margin-top: 5%;
        font-family: 'Raleway', sans-serif;
        font-size: 1.5vw;
        border-left: 11px solid #000;
        line-height: 40px;
        width: 95%;
        padding-left: 2%;
    }
`
function History() {

  return (
      
    <HistoryContainer>
        <Nav/>
        <Container>
            <h1>OUR HISTORY</h1>
        </Container>

        <SecondContainer>
            <Paragraph>
                The Manufacturers Association of Nigeria (MAN) was established in May, 1971 as a company limited by guarantee. The establishment of the Association was motivated by the desire to have a focal point of communication and consultation between industry on the one hand, and the government and general public on the other. Hitherto, there was no institutional organ whose central focus was to give meaning to the interests, problems and aspirations of the manufacturing sector.
            </Paragraph>

            <Paragraph>
                The establishment of the Manufacturers Association of Nigeria was to provide a platform for the private sector to formulate and articulate policy suggestions that would be complementary to governments efforts at policy formulation. MAN is in business to create a climate of opinion in this country in which manufacturers can operate efficiently and profitably for the benefit of all. As the collective voice of its members, MAN was established to promote and protect manufacturers collective interests.
            </Paragraph>

            <Paragraph>
                The establishment of the Manufacturers Association of Nigeria was therefore seen as a forum for the private sector to formulate and articulate policy suggestions that would be complementary to government’s efforts at policy formulation. MAN is in business to create a climate of opinion in this country in which manufacturers can operate efficiently and profitably for the benefit of all. As the collective voice of its members, MAN was established to promote and protect manufacturers’ collective interests.
            </Paragraph>
        </SecondContainer>

        <TimelineComponent>
            <TimeLineComponent/>
        </TimelineComponent>

        <Mission>
            <h1>OUR OBJECTIVES</h1>

            <ul>
                <li>Provide for manufacturers all over Nigeria the means of formulating, making known and influencing general policy in regard to industrial, labour, social, legal, training, and technical matters;</li>
                <li>To develop and promote the contribution of manufacturers to the national economy through government and otherwise, whose work may affect directly or indirectly the interests of manufacturers;</li>
                <li>To encourage a high standard of quality of members’ products through the collective and circulation of useful information and the provision of advice;</li>
                <li>To encourage the patronage of members’ products by Nigerians and by consumers in foreign countries;</li>
                <li>To communicate and liaise with kindred and other bodies, in the accomplishment of the objectives of the Association and on subjects of common interest.</li>
            </ul>

            <p>
            By pursuing these objectives, the Association hopes that members would be helped to play their full part in creating wealth on which national economic prosperity and social progress depend. Overall, the task of MAN is that of helping to promote policies for a more stable and buoyant economy without which industry cannot be efficient and financially healthy. In order to do this, the Association endeavors to put across its viewpoints at national, state and local levels. Such viewpoints are the products of research and the collective experience of member companies. The basic philosophy of the Association is to ensure the well-being of its members on which the livelihood of their management, workers, customers and suppliers depends.
            </p>
        </Mission>
        <Footer/>
    </HistoryContainer>
  )
}

export default History