import React from 'react'
import styled from 'styled-components'
import bg from '../Assets/bg.jpeg'
import logo2 from '../Assets/l5.jpeg'
import logo4 from '../Assets/nig.gif'
import vec from '../Assets/vector.jpg'
import map from '../Assets/map.jpeg'
import AnimatedText from 'react-animated-text-content';
import CarouselComponent from './CarouselComponent';
import MyVerticallyCenteredModal from './MyVerticallyCenteredModal';
import MyVerticallyCenteredModal2 from './MyVerticallyCenteredModal2';
import MyVerticallyCenteredModal3 from './MyVerticallyCenteredModal3';
import { Link } from 'react-router-dom';
import Footer from './Footer'
import Nav from './Nav'
import Typicall from './Typicall'


const Container = styled.div`
    width: 100%;
    min-height: 100vh;
    overflow: hidden!important;
`
const Section = styled.div`
    width: 100%;
    height: auto;
    position: relative;
    background: linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${bg});
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 30%;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}

`
const First = styled.div`
@media (max-width:480px) {
    flex-direction: column;
    justify-content: center;
    gap: 5%;
}
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: space-between;
    padding: 2%;
    align-items: center;
    position: relative;
`
const Left = styled.div`
    @media (max-width:480px) {
        width: 100%;
    }
    padding: 2%;
    width: 50%;
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        text-align: left;
        font-family: 'Lato', sans-serif;
        color: #fff;
        font-size: 3vw;
        font-weight: 900;
        text-align: left;
    }p{
        @media (max-width:480px) {
            font-size: 1rem;
        }
        color: #fff;
    }
`
const Right = styled.div`
    @media (max-width:480px) {
        width: 100%;
        height: 20vh;
    }
    width: 40%;
    border-radius: 12px;
    background: #ffffff3a;
    height: 30vh;
    display: flex;
    align-items: center;
    justify-content: center;
    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
        }
        color: #fff;
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        font-weight: 900;
        text-align: center;
    }
`
const Dropdwn = styled.div`
    @media (max-width:480px) {
        margin-left: 5%;
        top: 90%;
    }
    margin-left: 45%;
    width: 10%;
    height:100px;
    position: absolute;
    top: 80%;
    display: flex;
    justify-content: center;
    align-items: center;
.arrows {
  width: 60px;
  height: 72px;
  position: absolute;
  left: 50%;
  margin-left: -30px;
  bottom: 20px;
}
.arrows path {
    stroke: #fff;
    fill: transparent;
    stroke-width: 1px;  
    animation: arrow 2s infinite;
    -webkit-animation: arrow 2s infinite; 
    cursor: pointer;
}

    @keyframes arrow
    {
    0% {opacity:0}
    40% {opacity:1}
    80% {opacity:0}
    100% {opacity:0}
}
@-webkit-keyframes arrow /*Safari and Chrome*/
{
    0% {opacity:0}
    40% {opacity:1}
    80% {opacity:0}
    100% {opacity:0}
}
.arrows path.a1 {
    animation-delay:-1s;
    -webkit-animation-delay:-1s; /* Safari 和 Chrome */
}

.arrows path.a2 {
    animation-delay:-0.5s;
    -webkit-animation-delay:-0.5s; /* Safari 和 Chrome */
}

.arrows path.a3 { 
    animation-delay:0s;
    -webkit-animation-delay:0s; /* Safari 和 Chrome */
}
`
const CoreValues = styled.h1`
    @media (max-width:480px) {
        font-size: 2rem;
    }
    margin-top: 10%;
    display: flex;
    font-family: 'Lato', sans-serif;
    justify-content: center;
    align-items: center;
    font-size: 3vw;
    margin-bottom: 5%;
    font-weight: 800;
    color: #03030c;
`
const Second = styled.div`
    @media (max-width:480px) {
        height: 50vh;
    }
    width: 95%;
    margin:auto;
    height: 100vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2})center center fixed;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
`

const Meet = styled.div`
    @media (max-width:480px) {
        display: none;
    }
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: 'Lato', sans-serif;
    font-size: 3vw;
    margin-top: 5%;
    margin-bottom: 5%;
    font-weight: 800;
    color: #03030c;;
`
const ThirdSEction = styled.div`
    width: 100%;
    height: 100vh;
    display: flex;
    background-size: cover;
    background: url(${vec});
    justify-content: space-between;
    position: relative;
    align-items: center;
    padding: 5%;
    transition: all .3s linear;
    clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 0% 93%);
    @media (max-width:480px) {
        display: none;
    }
    .card{
        @media (max-width:480px) {
            width: 95%;
        }
        width: 25%;
        height: 100%;
        background: #03030c;
        color: #fff;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        display: flex;
        justify-content: flex-start;
        gap: 10%;
        flex-direction: column;
        align-items: center;
        border-radius: 5px;
        padding: 2%;
        cursor: pointer;
        p{
            font-family: 'Raleway', sans-serif;
            font-size: 1.5vw;
            text-align: center;
        }
        .top{
            width: 250px;
            height: 250px;
            img{
                width: 100%;
                height: 100%;
                object-fit: cover;
            }
        }
    }  
`
const FourthSection = styled.div`
    width: 100%;
    padding: 2%;
    height: auto;
    background:  url(${vec}),fixed;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
`
const Mandate = styled.div`
    width: 100%;
    height: 80vh;
    background: #03030ccd;
    border-radius: 12px;
    padding: 2%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 5%;
    p{
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        line-height: 30px;
        color:#fff;
    }
`
const Head3 = styled.h1`
    margin-top: 5%;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 3vw;
    font-weight: 900;
    text-align: center;
    color: #03030c;
    font-family: 'Lato', sans-serif;
`

const Btn =styled.button`
    margin-top: 5%;
    margin-left: 50%;
    transform: translate(-50%, -50%);
    border: none;
a{
    display: block;
    width: 200px;
    height: 50px;
    line-height: 40px;
    font-size: 18px;
    font-family: sans-serif;
    text-decoration: none;
    color: #03030c;
    border: 1px solid #03030c;
    letter-spacing: 2px;
    text-align: center;
    position: relative;
    transition: all .35s;
}
a span{
  position: relative;
  z-index: 2;
}
a:after{
  position: absolute;
  content: "";
  top: 0;
  left: 0;
  width: 0;
  height: 100%;
  background: #03030c;
  transition: all .35s;
}
a:hover{
  color: #fff;
}
a:hover:after{
  width: 100%;
}
`
const Locate = styled.h1`
    @media (max-width:480px) {
        font-size: 2rem;
    }
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 2.5vw;
    font-family: 'Lato', sans-serif;
    font-weight: 800;
    color: #03030c;
    margin-bottom: 5%;
`

const FifthSection = styled.div`
    @media (max-width:480px) {
        flex-direction: column-reverse;
        justify-content: center;
        gap: 5%;
    }
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 2%;
    background: linear-gradient(90deg, #0e0215a1 0%, #1d1b1ba3 32%, #14110da6 100%),url(${map})center center fixed;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
`
const FifthLeft = styled.div`
    @media (max-width:480px) {
        width: 100%;
    }
    width: 50%;
    padding: 1%;
    h1{
        @media (max-width:480px) {
            font-size: 1.5rem;
        }
        font-size: 2.5vw;
        font-weight: 900;
        text-align: left;
        color: #fff;
        font-family: 'Lato', sans-serif;
    }
    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
        }
        line-height: 40px;
        font-size:  1.5vw;
        color: #fff;
    }
    button{
        @media (max-width:480px) {
            font-size: 1rem;
            width: 40%;
            height: 6vh;
        }
        height: 8vh;
        width: 30%;
        font-size: 1.3vw;
        border: none;
        border-radius: 5px;
        background: #a5de08;
        color: #fff;
        transition: all .5s linear;
        &:hover{
            background:#03030c;
        }
    }
`
const FifthRight = styled.div`
    @media (max-width:480px) {
        display: none;
    }
    width: 50%;
    height: 100%;
    background: url(${logo4});
    background-size: contain;
    background-repeat: no-repeat;
`
const BeforeFourth = styled.div`
    @media (max-width:480px) {
        flex-direction: column;
        margin-top: 10%;
    }
    width: 100%;
    height: 100vh;
    display: flex;
    gap: 5%;
    justify-content: center;
    align-items: center;
    padding: 2%;
`

const Bleft = styled.div`
    @media (max-width:480px) {
        width: 100%;
    }
    width: 45%;
    height: 70%;
    position: relative;
    figure{
        width: 100%;
        height: 100%;
        position: absolute;
        overflow: hidden;
        z-index: 30;
        img{
            width: 100%;
            height: 100%;
            object-fit:cover;
            transition: all 1s linear;
        }
        &:hover{
            img{
                transform: scale(1.1);
            }
        }
    }
    .overlay{
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        background-color: #10120bda;
        font-family: 'Lato', sans-serif;
        overflow: hidden;
        width: 100%;
        height: 0;
        transition: .5s ease;
        padding-left: 2%;
        z-index: 40;
        h3{
            @media (max-width:480px) {
                font-size: 2rem;
            }
            font-size: 2wv;
            color: #fff;
            font-weight: 500;
        }
        p{
            @media (max-width:480px) {
                font-size: 1.2rem;
            }
            font-size: 1.5vw;
            color: #fff;
            font-weight: 500;
        }
        button{
            @media (max-width:480px) {
                font-size: 1.2rem;
                width: 35%;
            }
            width: 25%;
            height: 6vh;
            font-size:1.2vw;
            border: none;
            border-radius: 5px;
            color: #03030c;
            transition: all .5s linear;
            &:hover{
                background: #03030c;
                color: #fff;
            }
        }
    }
    &:hover .overlay{
        height: 50%;
        padding-top: 2%;
    }
`

function Home() {
    const [modalShow, setModalShow] = React.useState(false);
    const [modalShow2, setModalShow2] = React.useState(false);
    const [modalShow3, setModalShow3] = React.useState(false);
  return (
    <Container>
        <Nav/>
        <Section>
        <First>
            <Left>
                <h1>
                    The Manufacturers Association of Nigeria (MAN)
                </h1>
                <p>
                    Promoting and protecting the manaufacturers collective Interest, and creating sustainable value for our stakeholders
                </p>
            </Left>
            <Right>
                <p><Typicall/></p>
            </Right>
            <Dropdwn>
                <a href="#second">
                    <svg class="arrows">
                    <path class="a1" d="M0 0 L30 32 L60 0"></path>
                    <path class="a2" d="M0 20 L30 52 L60 20"></path>
                    <path class="a3" d="M0 40 L30 72 L60 40"></path>
                    </svg>
                </a>
            </Dropdwn>
        </First>
        </Section>
        <CoreValues>
            OUR CORE VALUES
        </CoreValues>

        <Second id='second'>
          <CarouselComponent/>
        </Second>

        <Meet>
            The Executive Members
        </Meet>

        <ThirdSEction>
            <div className="card" onClick={() => setModalShow(true)}>
                <div className="top">
                    <img src="/SEGUN.jpg" alt="" />
                </div>
                <div className="mid">  
                    <p><b>SEGUN AJAYI-KADIR, mni</b> </p>
                </div>
                <div className="bottom">
                    <p>DIRECTOR GENERAL</p>
                </div>
            </div>

            <div className="card" onClick={() => setModalShow2(true)}>
                <div className="top">
                    <img src="/pres.png" alt="" />
                </div>
                <div className="mid">  
                    <p><b>Engr. Mansur Ahmed</b></p>
                </div>
                <div className="bottom">
                    <p>PRESIDENT</p>
                </div>
            </div>

            <div className="card" onClick={() => setModalShow3(true)}>
                <div className="top">
                    <img src="/Rev.jpg" alt="" />
                </div>
                <div className="mid">  
                    <p><b>Rev. Isaac Adefemi Agoye</b></p>
                </div>
                <div className="bottom">
                    <p>National Treasurer</p>
                </div>
            </div>
            <MyVerticallyCenteredModal
                show={modalShow}
                onHide={() => setModalShow(false)}
            />

            <MyVerticallyCenteredModal2
                show={modalShow2}
                onHide={() => setModalShow2(false)}
            />

            <MyVerticallyCenteredModal3
                show={modalShow3}
                onHide={() => setModalShow3(false)}
            />
        </ThirdSEction>

        <BeforeFourth>
            <Bleft>
                <figure>
                    <img src='/engine1.jpeg' alt="n/a" />
                </figure>
                <div className="overlay">
                    <h3>Services</h3>
                    <p>We are    "... the Manufacturers’ Solution Hub"</p>
                    <button>What we offer</button>
                </div>        
            </Bleft>
            <Bleft>
                <figure>
                    <img src='/engine2.jpeg' alt="n/a" />
                </figure>
                <div className="overlay">
                    <h3>Join Us!</h3>
                    <p>Come join the league of Manufacturers with credibility in Nigeria!</p>
                    <button>Register</button>
                </div>
            </Bleft>
        </BeforeFourth>

        <Locate>
            OUR LOCATION
        </Locate>

        <FifthSection>
          <FifthLeft>
            <h1>The Association has one National Secretariat</h1>
            <p>
                <AnimatedText
                    type="words" // animate words or chars
                    animation={{
                        x: '200px',
                        y: '-20px',
                        scale: 1.1,
                        ease: 'ease-in-out',
                    }}
                    animationType="float"
                    interval={0.06}
                    duration={0.8}
                    tag="p"
                    className="animated-paragraph"
                    includeWhiteSpaces
                    threshold={0.1}
                    rootMargin="20%"
                    >
                        The National Secretariat of MAN is headed by a Director General, who is the Chief Executive Officer. Assisted by a complement of staff, the Director General executes on a daily basis, the policy decisions/directives of the National Coucil. The Secretariat is designed and geared to provide specialized services to individual members as well as groups, covering major areas of the manufacturing operations.
                </AnimatedText>
            </p>
            <button>View Locations</button> 
          </FifthLeft>

          <FifthRight>

          </FifthRight>
        </FifthSection>

        <FourthSection data-aos="fade-up" data-aos-duration="3000">
            <Head3>Our Mandate</Head3>
            <Mandate>
                <p>
                    Manufacturers Association of Nigeria (MAN) receives its mandate from the National Council, fourteen (14) Branch Councils across the country, and ten (10) Sectoral Groups. In addition, five (5) standing committees, nine (9) Ad-Hoc Committee and seventy-six (76) Subsectoral Groups.
                </p>
                <p>
                    This engagement process reaches over 3000 MAN members who have a direct say in what we do and how we do it, from renewing our work strategies to discussing the key business issues of the day and re-tooling our influence.
                </p>
                <p>
                    Each of our national council and branch council members are elected to a term of office. Our standing committee members are invited to join voluntarily based on their sector experience and technical expertise.
                </p>
            </Mandate>
            <Btn><Link to='/'><span>View More</span></Link></Btn>
        </FourthSection>
        
        <Footer/>
    </Container>
  )
}

export default Home