import React from 'react'
import styled from 'styled-components'
import logo2 from '../Assets/who.webp'
// import Footer from './Footer'
// import Nav from './Nav'

const HowreWeWorkContainer = styled.div`
    width: 100%;
    min-height: 100vh;
    overflow: hidden;
    border: 11px solid #000;
`
const Container = styled.div`
@media (max-width:480px) {
        height: 70vh;
    }
    width: 100%;
    height: 80vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        color: #fff;
        font-size: 5vw;
    }
`
function HowWeWork() {
  return (
    <HowreWeWorkContainer>
        <Container>
            <h1>WHO WE ARE</h1>
        </Container>
    </HowreWeWorkContainer>
  )
}

export default HowWeWork