import React from 'react'
import styled from 'styled-components'
import logo2 from '../Assets/where.jpeg'
import logo3 from '../Assets/where2.jpeg'
import Table from 'react-bootstrap/Table'
import Footer from './Footer'
import Nav from './Nav'

const WhereWeOperateContainer = styled.div`
    width: 100%;
    min-height: 100vh;
    overflow: hidden;
`
const Container = styled.div`
    @media (max-width:480px) {
        height: 70vh;
    }
    width: 100%;
    height: 80vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 90%;
    display: flex;
    justify-content: center;
    align-items: center;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        color: #fff;
        font-size: 5vw;
    }
`
const Second = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 40vh;
    padding: 2%;
    h1{
    @media (max-width:480px) {
        font-size: 2rem;
    }
    font-size: 2vw;
    font-family: 'Lato', sans-serif;
    font-weight: 900;
}
p{
    @media (max-width:480px) {
        font-size: 1.2rem;
    }
    font-size: 1.5vw;
    font-family: 'Lato', sans-serif;
}
`
const Third = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 40vh;
    padding: 2%;
    h1{
    @media (max-width:480px) {
        font-size: 2rem;
    }
    font-size: 2vw;
    font-family: 'Lato', sans-serif;
    font-weight: 900;
}
p{
    @media (max-width:480px) {
        font-size: 1.2rem;
    }
    font-size: 1.5vw;
    font-family: 'Lato', sans-serif;
}

`
const Fourth = styled.div`
    @media (max-width:480px) {
        height: auto;
        flex-direction: column;
        margin-bottom: 5%;
    }
    width: 100%;
    height: 70vh;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 5%;
    padding: 2%;
    background:  linear-gradient(90deg, #0e021583 0%, #17010165 32%, #0f140d70 100%),url(${logo3}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 90%;
`
const Card = styled.div`
    @media (max-width:480px) {
        width: 95%;
        height: auto;
        margin-top: 10%;
    }
    width: 35%;
    height: 50vh;
    padding: 2%;
    border-radius: 12px;
    box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
    background: #03030c;
    color: #fff;
    p{
    @media (max-width:480px) {
        font-size: .7rem;
    }
    font-size: 1.2vw;
    font-family: 'Lato', sans-serif;
    font-weight: 500;
}
`
const Fifth = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 40vh;
    padding: 2%;
    h1{
    @media (max-width:480px) {
        font-size: 2rem;
    }
    font-size: 2vw;
    font-family: 'Lato', sans-serif;
    font-weight: 900;
}
p{
    @media (max-width:480px) {
        font-size: 1.2rem;
    }
    font-size: 1.5vw;
    font-family: 'Lato', sans-serif;
}

`
const Sixth = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 95%;
    min-height: 100vh;
    margin:auto;
`
function WhereWeOperate() {
  return (
    <WhereWeOperateContainer>
        <Nav/>
        <Container>
            <h1>WHERE WE OPERATE</h1>
        </Container>

        <Second>
            <h1>
                The Association has one National Secretariat
            </h1>
            <p>
                The National Secretariat of MAN is headed by a Director General, who is the Chief Executive Officer. Assisted by a complement of staff, the Director General executes on a daily basis, the policy decisions/directives of the National Coucil. The Secretariat is designed and geared to provide specialized services to individual members as well as groups, covering major areas of the manufacturing operations.
            </p>
        </Second>

        <Third>
            <h1>MAN Corporate Officies</h1>
            <p>The Head Office of MAN, named MAN House, is strategically located at No. 77, Obafemi Awolowo Way, Ikeja, Lagos State, Nigeria, the twin-block edifice is on a plot of land measuring 2,860.771sq meters benevolently leased to the Association for 99 years by its first president, Chief T. Adeola Odutola, the Ogbeni-Oja of Ijebu-Ode.</p>
        </Third>

        <Fourth>
            <Card>
                <p>MAN House</p>
                <p>77, Obafemi Awolowo Way</p>
                <p>Ikeja, Lagos State, Nigeria</p>
                <p>Tel: 01-4542700, 01-4542701</p>
                <p>Email: man@manufacturersnigeria.org</p>
                <p>Website: www.manufacturersnigeria.org</p>
            </Card>
            <Card>
                <p>MAN Abuja Liaison Office</p>
                <p>Suit 202, Adamawa Plaza,</p>
                <p>Central Business District 1,</p>
                <p>Abuja</p>
                <p>Tel: 08062409324, 07089398541</p>
                <p>Email: manabujaliaison@manufacturersnigeria.org</p>
            </Card>
        </Fourth>

        <Fifth>
            <h1>Branch Offices</h1>
            <p>As a result of developments in the political structure of the country, Branches were planned for the 36 states of the federation and Abuja, to ensure that the needs of manufacturers at both the State and Local Governement levels are met. However, due to the rate of industrial development in some states, these states have been grouped together until such a time that there are enough member companies from each state to form a Branch. All Branch offices are headed by full-time Executive Secretaries and a compliment of staff.</p>
        </Fifth>

        <Sixth>
            <Table responsive>
                <thead>
                <tr>
                    <th>Location</th>
                    <th>Address</th>
                    <th>Tel</th>
                    <th>Email</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td><b>MAN Abuja</b> </td>
                    <td>Suite 202, Adamawa Plaza, Central Business District 1, Abuja</td>
                    <td>Tel: 08036131330, 07089398541,</td>
                    <td>manabujabranch@manufacturersnigeria.org; saokpe@yahoo.co.uk; sunday.adejoh@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Anambra/Enugu/Ebonyi</b></td>
                    <td>18 (Formerly 2A) Chime Avenue, New Haven P.O.Box 9536, Uwani-Enugu Tel: 08037181922,</td>
                    <td> 08037181922</td>
                    <td>mananambraenugu@manufacturersnigeria.org; enuguman2012@gmail.com; sunday.sotomi@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Ikeja</b></td>
                    <td>2A, Akilo Road Ogba, Lagos</td>
                    <td>08062749019, 012950226 Secretariat, 09037343474 MAN Fire Service</td>
                    <td>manikeja@manufacturersnigeria.org, oluchi.odimuko@manufacturersnigeria.org manikeja1@yahoo.com</td>
                </tr>

                <tr>
                    <td><b>MAN Apapa</b></td>
                    <td>Shalom Street, beside Brian Premier School By Lagoon Estate Ark, off Okota Road, Amuwo Odofin Industrial Estate, Amuwo, Lagos</td>
                    <td>08035440843, 09062874863</td>
                    <td>manapapa@manufacturersnigeria.org, manapapabranch@gmail.com</td>
                </tr>

                <tr>
                    <td><b>MAN Ogun</b></td>
                    <td>Km.4, (Beside Oba T. Dada Market) Ota, Idiroko Road, Sango Ota, Ogun State</td>
                    <td>08069301620,</td>
                    <td>manogun@manufacturersnigeria.org, manogun25@gmail.com</td>
                </tr>

                <tr>
                    <td><b>MAN Edo/Delta</b></td>
                    <td>Plot 4, AlexandarOgun Road, Evboriria Industrial Estate, Km 7, Sapele Road Tel: 08060642427,</td>
                    <td>08060642427,</td>
                    <td>manedodelta@manufacturersnigeria.org, lucky.amachree@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Bauchi/Benue/Plateau</b></td>
                    <td>7, Suzi Garden, TafawaBalewa Street P.O.Box 862, Jos</td>
                    <td>08030627250</td>
                    <td>manbauchibenue@manufacturersnigeria.org, manbauchibenue@gmail.com augustine.egili@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Kano Bompai</b></td>
                    <td>Kano Foundation Building 15, B.U.K. Road, Kano Tel: 08035354133; 08023097399,</td>
                    <td>08035354133; 08023097399,</td>
                    <td>mankanosharada@manufacturersnigeria.org; attahir.gwazo@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Kano Sharada/Challawa</b></td>
                    <td>Kano Foundation Building 15, B.U.K. Road, Kano.</td>
                    <td>08035354133; 08023097399,</td>
                    <td>attahir.gwarzo@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Imo/Abia</b></td>
                    <td>15A (19A) Wetheral Road, Flat No.2 P.O.Box 973, Owerri</td>
                    <td>08068501530</td>
                    <td>manimoabia@manufacturersnigeria.org; henryprince4real@yahoo.com; cyprian.nnadozie@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Oyo/Ondo/Osun/Ekiti</b></td>
                    <td>5, Ighodaro Road, Jericho P.O.Box 16159, Ibadan</td>
                    <td>07037132642</td>
                    <td>attahir.gwarzo@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Rivers</b></td>
                    <td>Plot 26, Danjuma Drive, Behind Savannah Bank P.M.B. 082, Trans Amadi, Port Harcourt</td>
                    <td>09085296322; 09098573223</td>
                    <td>manrivers@manufacturersnigeria.org; manrivers23@yahoo.com; chibuzo.eze@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Kaduna North</b></td>
                    <td>No.1, KeffiClose Opp. BOC Gases Nig. Plc P.O.Box 4361, Kaduna</td>
                    <td>07065640209</td>
                    <td>mankaduna@manufacturersnigeria.org; Muhammad.muhammad@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Kaduna South</b></td>
                    <td>No.1, KeffiClose Opp. BOC Gases Nig. Plc P.O.Box 4361, Kaduna</td>
                    <td>07065640209,</td>
                    <td>mankaduna@manufacturersnigeria.org; Muhammad.muhammad@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Crossriver/Akwa-Ibom</b></td>
                    <td>Nil</td>
                    <td>07064372015, 08097393470</td>
                    <td>mancrossriverakwa-ibom@manufacturersnigeria.org; offiong.essien@manufacturersnigeria.org</td>
                </tr>

                <tr>
                    <td><b>MAN Kwara/Kogi</b></td>
                    <td>Plot 1, Irewolede Road, Along Yidi Road, Ilorin, Kwara State.</td>
                    <td>08035283467</td>
                    <td>mankwarakogi@manufacturersnigeria.org; mankwarakogi@hotmail.co.uk; gbenga.adeola@manufacturersnigeria.org</td>
                </tr>
                </tbody>
            </Table>
        </Sixth>

        <Fifth>
            <h1>MAN Sectoral Groups and Sub-Sectoral Groups</h1>
            <p>In order to cater for memebers who have near homogenous or sector-specific products, MAN has ten (10) Sectoral Groups and seventy seven (77) Sub-Sectoral Groups. The Groups are serviced by full-time Sectoral Executives located at the National Secretariat of the Association.</p>
        </Fifth>

        <Sixth>
            <Table responsive data-aos="fade-up" data-aos-duration="3000">
                <thead>
                <tr>
                    <th>Food, Beverages & Tobacco </th>
                    <th>Chemical & Pharmaceuticals </th>
                    <th> Domestic & Industrial Plastics, Foam & Rubber </th>
                    <th>Metal, Iron & Steel & Fabricated Metal Product </th>
                    <th>paper,Printing & Publishing </th>
                    <th>Electrical/ Electronic </th>
                    <th> Wood & Furniture </th>
                    <th>Non Metallic Minerals </th>
                    <th>Textiles,Leather </th>
                    <th>Vehicle Assembly </th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td> Beer</td>
                    <td> Paints Vanishes and Allied Products</td>
                    <td>Rubber Products</td>
                    <td>Association of Steel Pipe Manufacturers</td>
                    <td>Chemical and Stationery Manufacturers</td>
                    <td>Electronics</td>
                    <td>Wood Products and Furniture</td>
                    <td>Glass-Manufacturers</td>
                    <td>Textile and Wearing Apparel Manufacturers</td>
                    <td>Boat/Ship Building</td>
                </tr>

                <tr>
                    <td>Starch and Other Miscellaneous Food Products</td>
                    <td>Industrial Medical and Special Gases</td>
                    <td>Domestic and Industrial Plastics</td>
                    <td>Metal Packaging Manufacturers</td>
                    <td>Printing Publishing and Packagin</td>
                    <td>Refrigerators and Air-conditioning/Domestic Appliances</td>
                    <td>Plywood and Particle Board Manufacturers</td>
                    <td>Ceramics Manufacturers</td>
                    <td>Leather Products Manufacturers</td>
                    <td>Automobile Components Manufacturers</td>
                </tr>

                <tr>
                    <td>Flavouring</td>
                    <td>Soap and Detergent</td>
                    <td>Foam Manufacturers</td>
                    <td>Metal Manufacturers and Fabricators</td>
                    <td>Pulp Paper and Paper Products</td>
                    <td>Electric Bulb/Lamps Accessories and Fittings</td>
                    <td></td>
                    <td>School Chalks and Crayons</td>
                    <td>Carpet and Rug Manufacturers</td>
                    <td>Electric Generators Assemblers</td>
                </tr>

                <tr>
                    <td>Soft Drinks and Carbonated Water</td>
                    <td>Agro Chemicals (Fertilizers and Pesticides)</td>
                    <td>Suitcases and Bags Manufacturers</td>
                    <td>Association of Primary Aluminium Producers</td>
                    <td>Sanitary Towels Napkins and Diapers</td>
                    <td>Electrical Power Control and Distribution Equipment</td>
                    <td></td>
                    <td>Cement Manufacturers</td>
                    <td>Footwear Manufacturers</td>
                    <td> Miscellaneous Machine and Equipment Manufacturers</td>
                </tr>

                <tr>
                    <td>Flour and Grain Milling</td>
                    <td>Pharmaceuticals</td>
                    <td>Flexible Packaging Manufacturers</td>
                    <td>Enamel Wares Manufacturers</td>
                    <td></td>
                    <td>Cable and Wire</td>
                    <td></td>
                    <td></td>
                    <td>Cordage Rope and Twine Manufacturers</td>
                    <td>Bicycle-Manufacturers</td>
                </tr>

                <tr>
                    <td>Meat and Fish</td>
                    <td>Safety Matches</td>
                    <td></td>
                    <td>Welding Electrode Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Horological</td>
                    <td>Motorcycle-Assemblers</td>
                </tr>

                <tr>
                    <td>Tea Coffee and other Beverages</td>
                    <td>Dry Cell Battery</td>
                    <td></td>
                    <td>Galvanized Iron Sheets Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Motor-Vehicle-Assemblers</td>
                </tr>

                <tr>
                    <td>Dairy Products</td>
                    <td>Petroleum Products</td>
                    <td></td>
                    <td>Nail and Wire Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Fruit Juice</td>
                    <td>Gramophone Records and Musical Tapes Manufacturers</td>
                    <td></td>
                    <td>Steel Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Tobacco</td>
                    <td>Tapes Manufacturers</td>
                    <td></td>
                    <td>Foundry</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Biscuits and Bakery Products</td>
                    <td>Candle Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Animal Feeds</td>
                    <td>Printing Ink Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Sugar</td>
                    <td>Toiletries and Cosmetics</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Distillery and Blending of Spirit</td>
                    <td>Basic Industrial Chemicals</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Cocoa Chocolate and Sugar Confectionery</td>
                    <td>Automotive Battery</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Vegetable and Edible Oil</td>
                    <td>Resin Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <td>Poultry Group</td>
                    <td>Ball Point Pen Manufacturers</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </Table>
        </Sixth>
        <Footer/>
    </WhereWeOperateContainer>
  )
}

export default WhereWeOperate