import React from 'react'
import styled from 'styled-components'
import logo2 from '../Assets/how.jpg'
import Footer from './Footer'
import Nav from './Nav'

const WhoAreWeContainer = styled.div`
    width: 100%;
    min-height: 100vh;
    overflow: hidden;
`
const Container = styled.div`
    @media (max-width:480px) {
        height: 70vh;
    }
    width: 100%;
    height: 80vh;
    background:  linear-gradient(90deg, #0e0215ca 0%, #170101cf 32%, #0f140dc9 100%),url(${logo2}) center fixed ;
    background-size: cover;
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    background-position: 10% 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    -webkit-animation: kenburns-left 5s ease-out reverse forwards;
	animation: kenburns-left 5s ease-out reverse forwards;
    /* ----------------------------------------------
 * Generated by Animista on 2022-5-29 21:50:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-left
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
@keyframes kenburns-left {
  0% {
    -webkit-transform: scale(1) translate(0, 0);
            transform: scale(1) translate(0, 0);
    -webkit-transform-origin: 16% 50%;
            transform-origin: 16% 50%;
  }
  100% {
    -webkit-transform: scale(1.25) translate(-20px, 15px);
            transform: scale(1.25) translate(-20px, 15px);
    -webkit-transform-origin: left;
            transform-origin: left;
  }
}
    h1{
        @media (max-width:480px) {
            font-size: 2rem;
        }
        color: #fff;
        font-size: 5vw;
    }
`
const Second = styled.div`
    @media (max-width:480px) {
        flex-direction: column;
    }
    background: #fbfbff;
    width: 100%;
    min-height: 100vh;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    padding: 2%;
`
const Card = styled.div`
    @media (max-width:480px) {
        width: 95%;
        margin-top: 5%;
        justify-content: space-between;
        height: auto;
    }
    width: 30%;
    height: 50vh;
    background: #ffe8d1;
    display: flex;
    margin-bottom: 5%;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    border-radius: 12px;
    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
    gap: 5%;
    .top{
        @media (max-width:480px) {
            margin-bottom: 5%;
        }
        width: 50px;
        height: 50px;
        background: #fff;
        font-weight: 900;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    h1{
        @media (max-width:480px) {
            font-size: 1.2rem;
        }
        text-align: center;
        font-size: 2vw;
        font-weight: 900;
        font-family: 'Lato', sans-serif;
    }
    p{
        @media (max-width:480px) {
            font-size: 1rem;
        }
        text-align: center;
        font-size: 1.2vw;
        font-family: 'Lato', sans-serif;
        padding: 1%;
    }
    &:nth-child(2){
        background: #e9f5ff;
    }
    &:nth-child(3){
        background: #effaf5;
    }
    &:nth-child(4){
        background: #e9f5ff;
    }
    &:nth-child(5){
        background: #effaf5;
    }
    &:nth-child(6){
        background: #edebff;
    }
`
const Third = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 100vh;
    padding: 2%;
    h1{
        @media (max-width:480px) {
            font-size: 1.2rem;
            text-align: center;
        }
        font-size: 2vw;
        font-family: 'Lato', sans-serif;
        font-weight: 900;
        margin-top: 2%;
    }
    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
            padding-left: 5%;
        }
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        margin-top: 2%;
    }
    li{
        @media (max-width:480px) {
            font-size: 1rem;
        }
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        margin-top: 2%;
    }
`
const Fourth= styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 50vh;
    padding: 2%; 
    h1{
        @media (max-width:480px) {
            font-size: 1.2rem;
            text-align: center;
        }
        font-size: 2vw;
        font-family: 'Lato', sans-serif;
        font-weight: 900;
        margin-top: 2%;
    }
    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
            padding-left: 5%;
        }
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        margin-top: 2%;
    }
`
const Fifth = styled.div`
    @media (max-width:480px) {
        height: auto;
    }
    width: 100%;
    height: 50vh;
    padding: 2%; 
    h1{
        @media (max-width:480px) {
            font-size: 1.2rem;
            text-align: center;
        }
        font-size: 2vw;
        font-family: 'Lato', sans-serif;
        font-weight: 900;
        margin-top: 2%;
    }
    p{
        @media (max-width:480px) {
            font-size: 1.2rem;
            padding-left: 5%;
        }
        font-size: 1.5vw;
        font-family: 'Lato', sans-serif;
        margin-top: 2%;
    }
`
function WHoAreWe() {
  return (
    <WhoAreWeContainer>
        <Nav/>
        <Container>
            <h1>HOW WE WORK</h1>
        </Container>

        <Second>
            <Card>
                <div className="top">1</div>
                <h1>EXECUTIVE COMMITTEE</h1>
                <p>The Association has a National Council, made up of a President, 8 Vice President, Treasurer, Chairmen of Branches, Chairmen of Sectoral Groups and elected members. Past Presidents of the Association are life members representing special interest on the Council.</p>
            </Card>

            <Card>
                <div className="top">2</div>
                <h1>NATIONAL COUNCIL</h1>
                <p>The Association has a National Council, made up of a President, 8 Vice President, Treasurer, Chairmen of Branches, Chairmen of Sectoral Groups and elected members. Past Presidents of the Association are life members representing special interest on the Council.</p>
            </Card>

            <Card>
                <div className="top">3</div>
                <h1>OUR MANDATE</h1>
                <p>Manufacturers Association of Nigeria (MAN) receives its mandate from the National Council, fourteen (14) Branch Councils across the country, and ten (10) Sectoral Groups. In addition, five (5) standing committees, nine (9) Ad-Hoc Committee and seventy-six (76) Subsectoral Groups</p>
            </Card>

            <Card>
                <div className="top">4</div>
                <h1>STANDING COMMITTEE</h1>
                <p>In addition to the Executive Committee, the Association has 5 Standing Committees, namely:</p>
                <ul>
                    <li>Economic Policy Committee,</li>
                    <li>Finance & Establishment Committee</li>
                    <li>Small and Medium Industries Committee</li>
                    <li>Corporate Affairs and Strategic Planning Committee,</li>
                    <li>Infrastructure Committee</li>
                </ul>
            </Card>

            <Card>
                <div className="top">5</div>
                <h1>AD-HOC COMMITTEE</h1>
                <p>Ad-hoc Committees are however constituted to deal with specific and usually temporary issues as circumstances may demand. There are also Study Groups that deal with subjects of special interests to the Association as they arise, such as transport, energy, and other expenses.</p>
            </Card>

            <Card>
                <div className="top">6</div>
                <h1>MAN EXPORT GROUP AND GAS USERS GROUP</h1>
                <p>To promote export of Nigerian goods, MAN has an Export Group. MAN also has a Gas Users Group.</p>
            </Card>
        </Second>

        <Third>
            <h1>MAN CODE OF CONDUCT</h1>
            <p>In order to promote and develop meaningful contribution of manufacturers to the national economy, the National Council laid down the following code of conduct for members of the Association:</p>

            <ul>
                <li>Endeavour to maintain in all aspects of their operations, a high level of business ethics and recognized standards, thus refraining from all business dealings of questionable nature, which could bring the Association or the manufacturing sector as a whole into disrepute.</li>
                <li>Demonstrate transparent commitment to Nigeria’s industrial objectives and policies; placing Nigeria’s best interest above all others and increasing the contribution of the manufacturing sector to the economy, and towards the improvement of the quality of life of Nigerians.</li>
                <li>Promote, encourage and improve quality standards and process control in all their manufacturing operations.</li>
                <li>Refer to the National Council of the Association, any disagreement between members of the Association for arbitration before either party can pursue such a matter further (if necessary) after Council’s intervention.</li>
            </ul>
        </Third>

        <Fourth>
            <h1>ANNUAL GENERAL MEETING</h1>
            <p>Every year, our members are invited to attend our Annual General Meeting. The Annual General Meeting is used to elect the Auditors, elect or re-elect council members and MAN President and vote on wide variety of resolutions.</p>
        </Fourth>

        <Fifth>
            <h1>ANNUAL REPORT</h1>
            <p>Every year, Manufacturers Association of Nigeria (MAN) publishes its Annual Reports which contains empirical based information, key highlights from the years’ activites and details on our financial information.</p>
        </Fifth>
        <Footer/>
    </WhoAreWeContainer>
  )
}

export default WHoAreWe